### ISSUE TITLE
Interfacing with Teensy 4

### ISSUE THREAD

**Issue by metanav** [mjs513/TMM-HB01B0-Camera#29]
I would like to connect Teensy 4.0 with Arducam hm01b0  (https://www.arducam.com/product/arducam-hm01b0-qvga-spi-camera-module-for-raspberry-pi-pico-2). I guess HM01B0_PJRC_CARRIER pinout should be followed in 4 bit mode? Can I change it with any Teensy 4 pins or there are specific GPIOs other than SDA/SCL? Is there anything else which I should modify?

**Comment by mjs513** [comment]
I believe you asked this same question on the Teensy forum.  See the answer in this post:
https://forum.pjrc.com/threads/67796-Teensy-4-0-with-HB01B0-camera?p=284433#post284433
